export enum ColorsRandomBackground {
  ALICEBLUE=("#F0F8FF"),BEIGE=("#F5F5DC"), AZURE=("#F0FFFF"),
  CORNSILK=("#FFF8DC"),FLORALWHITE=("#FFFAF0"), GHOSTWHITE=("#F8F8FF"), HONEYDEW=("#F0FFF0"), IVORY=("#FFFFF0"),
  LAVENDERBLUSH=("#FFF0F5"),LAVENDER=("#E6E6FA"),LEMONCHIFFON=("#FFFACD"),LIGHTGOLDENRODYELLOW=("#FAFAD2"),
  LIGHTCYAN=("#E0FFFF"), LIGHTYELLOW=("#FFFFE0"), MINTCREAM=("#F5FFFA"),MISTYROSE=("#FFE4E1"),SNOW=("#FFFAFA")
}
